name: Prettier Check

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  prettier:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Check out the branch from the fork or base repo
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Run Prettier Requirements Check
        run: npx prettier --check .
